### ISSUE TITLE
pb-paginate: The static result text should be customizable

### ISSUE THREAD

**Issue by plutonik-a** [eeditiones/tei-publisher-components#46]
The text is currently static and very generic, and should be extracted from the component.  
The component should be able to emit a number of results and the keyword to be passed to a sort of result-text component. This result-text component should process the received "hit count" number and the keyword (phrase), and users should be able to modify the content and layout of the result text.

Reasons / benefits: 
1. Custom apps might want to display a modified result text depending on the use case. 
2. For long result lists it's useful to have a second pagination on top and at the end of the list. With the current implementation the pagination would then display the static result text twice.

<img width="276" alt="Screenshot 2020-09-24 at 14 01 59" src="https://user-images.githubusercontent.com/1157669/94143036-88502480-fe6f-11ea-829b-5af9fb184576.png">

**Comment by tuurma** [comment]
please cf. documentation for https://unpkg.com/@teipublisher/pb-components@latest/dist/api.html#pb-paginate.0

foundLabel property can be used to achieve that, passing in either alternate i18key or static text to display. Both may include placeholder `{{count}}` for the number of results found by the query.
