### ISSUE TITLE
pb-paginate: The label text can't be configured without overwriting the "total" result string

### ISSUE THREAD

**Issue by plutonik-a** [eeditiones/tei-publisher-components#49]
Related to https://github.com/eeditiones/tei-publisher-components/issues/46

---

If I want to set a fixed label for the pagination (attribute `foundLabel`) I replace the entire string with a fixed one and the number counting the results will be dropped: 

~~~xquery
<span class="found">
    ${translate(this.foundLabel, { count: this.total })}
</span>
~~~~

This markup :
~~~html
<pb-paginate per-page="10" range="5" subscribe="results" found-label="Some custom label..."/>
~~~

Will result in:
~~~html
<span class="found">Some custom label...</span>
~~~

`count: this.total` will no longer be returned.

**Comment by tuurma** [comment]
@plutonik-a have you tried to provide a placeholder for the count

`<pb-paginate per-page="10" range="5" subscribe="results" found-label="Some custom {{count}} label..."/>`

**Comment by tuurma** [comment]
@plutonik-a If hardcoded solution doesn't work, I think in general you need to set a custom label via a custom language file. Cf. Publisher documentation chapter  on`Language versions > Project specific i18n files`
