### ISSUE TITLE
Missing translation in 7.0.0.-RC

### ISSUE THREAD

**Issue by daliboris** [eeditiones/tei-publisher-components#53]
Hello, I've found another untranslated texts on the main page.
### Original
![ODD-Tooltips-EN](https://user-images.githubusercontent.com/8056045/98425618-26055900-2096-11eb-97e8-11d687dd123a.png)
### Localized
![ODD-Tooltips-CZ](https://user-images.githubusercontent.com/8056045/98425617-256cc280-2096-11eb-99d4-cfe8a391bb97.png)

**Comment by tuurma** [comment]
Thanks, will look into it
