### ISSUE TITLE
Make sidebar (pb-drawer) customizable for aligning left or right

### ISSUE THREAD

**Issue by plutonik-a** [eeditiones/tei-publisher-components#61]
Currently the sidebar has a fixed layout and is aligning only with the left side of the page.
`https://github.com/eeditiones/tei-publisher-components/blob/master/src/pb-drawer.js`

~~~css
:host {
    display: block;
}
:host(.overlay) {
    position: fixed;
    width: 0;
    left: -448px;
    bottom: 0;
    height: 100vh;
    z-index: 1000;
    overflow: auto;
    display: block;
    transition: .5s;
}
:host([opened]) {
    left: 0;
    width: 448px;
    transition: .5s;
}
~~~

**Feature request:**  

Extract the alignment `left || right` together with the width as a customizable variable and leave the current layout as default, if not specified.

**Comment by wolfgangmm** [comment]
Fixed by 01df3f154cc1a962341418ef4ce7b1a4c0237247
